### ISSUE TITLE
Add table row sorting buttons in the filelist.html template

### ISSUE THREAD

**Issue by benlabbe** [pi314/nano-http-server#9]
I propose to add 3 sorting buttons and some javascript to the `filelist.html` template, so that the table of files can be sorted.

[filelist.zip](https://github.com/pi314/hfs/files/7037866/filelist.zip)

**Comment by pi314** [comment]
Hi @benlabbe, thank you for sending the patch.

This toy-like project was for learning Python, I didn't use it often as `python -m http.server` works for me most of the time, and that's why there were no any updates for 5 years.

Today I found a tool that is way better and useful than this project: https://github.com/svenstaro/miniserve

It supports column sorting, file uploading and displaying QR code (in Terminal!)

A small self-contained Python package is fascinating, though.
If you want to use this project, feel free to fork and make modifications on it!

Best Regards,
pi314

**Comment by benlabbe** [comment]
Glad to read your answer.
I effectively switched to miniserve.
Thankyou very much @pi314.
